# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

name: Deploy on openshift on staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: send generic webhook
        run: |
          curl -X POST -k https://api.ocp.stg.fedoraproject.org:6443/apis/build.openshift.io/v1/namespaces/maubot/buildconfigs/maubot-build/webhooks/${{secrets.MAUBOT_STG_GITHUB_SECRET}}/generic
